apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-web-app
  namespace: argocd
spec:
  destination:
    namespace: node-web-app-ns
    server: https://kubernetes.default.svc
  project: node-web-app-project
  source:
    path: node-web-app/
    repoURL: https://github.com/jmbayu/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
