---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opensearch
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 1.8.3
    helm:
      values: |
        service:
          type: LoadBalancer
          loadBalancerIP: "10.1.1.186"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true