---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  destination:
    namespace: db
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.1.6
    helm:
      values: |
        global:
          postgresql:
            auth:
              postgresPassword: "GeHeim"
              username: ""
              password: ""
              database: ""
              existingSecret: ""
        primary:
          service:
            type: LoadBalancer
            loadBalancerIP: "10.1.1.184"      
        image:
          debug: true
        auth:
          enablePostgresUser: true
          postgresPassword: "Geheim"
          replicationUsername: repl_user
        readReplicas:
          replicaCount: 2
        volumePermissions:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
