---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.8.9
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: persistence.storageClass
          value: nfs-client
        - name:: redis.replicas.persistence.storageClass
          value: nfs-client
        - name:: volumePermissions.enabled
          value: true
    syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
