---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: sealed-secrets
    targetRevision: 2.1.4
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.type
          value: LoadBalancer
        - name: service.port
          value: 8080
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
