apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: node-web-app-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: node-web-app-ns
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
