apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-web-app-pv-claim
  labels:
    app: node-web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi