apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-web-app-svc-label
  name: node-web-app-svc
  namespace: node-web-app-ns
spec:
  ports:
  - port: 58080
    targetPort: 8080
  selector:
    app: node-web-app
  type: LoadBalancer
  loadBalancerIP: 10.1.1.181
